### ISSUE TITLE
UninitializedPropertyAccessException in TerrainTile.getHeightBuffer

### ISSUE THREAD

**Issue by milansoliya4210** [WorldWindEarth/WorldWindKotlin#49]
Encountered a crash in WorldWind Android library while rendering the frame. The error log indicates an `UninitializedPropertyAccessException` in `TerrainTile.getHeightBuffer`.

2023-11-20 16:25:34.930 28325-28325 worldwind gov.adrde.pus E WorldWindow.doFrame: Exception while rendering frame in Choreographer callback '278387563661348' kotlin.UninitializedPropertyAccessException: lateinit property heightBufferKey has not been initialized at earth.worldwind.globe.terrain.TerrainTile.getHeightBuffer(TerrainTile.kt:65) at earth.worldwind.globe.terrain.BasicTessellator.prepareDrawableTerrain(BasicTessellator.kt:135) at earth.worldwind.globe.terrain.BasicTessellator.addTile(BasicTessellator.kt:110) at earth.worldwind.globe.terrain.BasicTessellator.addTileOrDescendants(BasicTessellator.kt:95) at earth.worldwind.globe.terrain.BasicTessellator.assembleTiles(BasicTessellator.kt:77) at earth.worldwind.globe.terrain.BasicTessellator.tessellate(BasicTessellator.kt:58) at earth.worldwind.frame.BasicFrameController.renderFrame(BasicFrameController.kt:26) at earth.worldwind.WorldWind.renderFrame(WorldWind.kt:499) at earth.worldwind.WorldWindow.renderFrame(WorldWindow.kt:425) at earth.worldwind.WorldWindow.doFrame(WorldWindow.kt:260) at android.view.Choreographer$CallbackRecord.run(Choreographer.java:964) at android.view.Choreographer.doCallbacks(Choreographer.java:790) at android.view.Choreographer.doFrame(Choreographer.java:721) at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951) at android.os.Handler.handleCallback(Handler.java:883) at android.os.Handler.dispatchMessage(Handler.java:100) at android.os.Looper.loop(Looper.java:214) at android.app.ActivityThread.main(ActivityThread.java:7356) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by ComBatVision** [comment]
How to reproduce this issue? Do you have any example?

**Comment by ComBatVision** [comment]
Fixed in 1.3.5.
